name: Create Release Deployment
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    name: Create Linux Release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      
      - name: Build Application
        run: |
          gcc emulate.c -lSDL2 -lSDL2main -o chip8
      
      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            chip8

  create-release:
    needs: [linux-build]
    runs-on: ubuntu-latest
    name: Create GitHub Release
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: CHIP-8 Emulator Release
          tag_name: v${{ github.run_number }}
          files: |
            linux-build/chip8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
